### ISSUE TITLE
Rename Contact commands

### ISSUE THREAD

**Issue by leslieyip02** [AY2425S1-CS2103T-F13-3/tp#148]
## Description

For clarity. Needs to be completed before continuing work on `Event` commands.

- [ ] `AddCommand` -> `AddContactCommand`
- [ ] `EditCommand` -> `EditContactCommand`
- [ ] `ListCommand` -> `ListContactCommand`
- [ ] `DeleteCommand` -> `DeleteContactCommand`

**Comment by Teddayz** [comment]
Should work now, thanks!
