### ISSUE TITLE
Update Parser

### ISSUE THREAD

**Issue by leslieyip02** [AY2425S1-CS2103T-F13-3/tp#153]
## Description

Since both there will be add, list, edit and delete commands for both `Contact` and `Event`, we should standardize the commmand usage.

- `-c` for `Client`
- `-v` for `Vendor`
- `-e` for `Event`

For instance, to add something:

```
add -c ...
add -v ...
add -e ...
```

This can be handled within `AddressBookParser`.

**Comment by Teddayz** [comment]
Resolved with Yizhong's PR
