### ISSUE TITLE
Unable to add multiple vendors for an event.

### ISSUE THREAD

**Issue by Teddayz** [AY2425S1-CS2103T-F13-3/tp#183]
![image](https://github.com/user-attachments/assets/ba0b777a-e7c9-4f7b-b30e-f5b8955eeb17)
Have not completed the feature of adding multiple contacts to the list of vendors for a particular event. 
Each event currently can only have 1 client and 1 vendor.

**Comment by yizhong187** [comment]
This is expected, similar to tags, you will need to use multiple prefixes. E.g. `v/2 v/3 v/4`
