### ISSUE TITLE
UG display bug

### ISSUE THREAD

**Issue by FYL2003** [AY2425S1-CS2103T-F13-3/tp#188]
<img width="843" alt="Screenshot 2024-11-01 at 11 44 30 PM" src="https://github.com/user-attachments/assets/fdddc603-3009-417d-894c-2007b4bb6155">
As showed, the tip should be in bold but currently **tip** is displayed

**Comment by Teddayz** [comment]
Also, can update the UG for the `event` portion. It should be outdated.
