### ISSUE TITLE
Edit Command Email field not accepting valid inputs according to constraint

### ISSUE THREAD

**Issue by yizhong187** [AY2425S1-CS2103T-F13-3/tp#201]
Similar to issue #200 

To reproduce: edit 1 e/i_____i@gmail.com

According to the constraint response: The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters. The local-part does not actually violate the constraint.

**Comment by FYL2003** [comment]
Related issue: #204

**Comment by leslieyip02** [comment]
Closed by #224.
