### ISSUE TITLE
Edit command enters 0 or negative index returns differently from enters a positive index

### ISSUE THREAD

**Issue by FYL2003** [AY2425S1-CS2103T-F13-3/tp#206]
<img width="756" alt="Screenshot 2024-11-03 at 8 53 29 PM" src="https://github.com/user-attachments/assets/4ac8d725-12d5-4887-b2e1-2baf4562b182">
<img width="752" alt="Screenshot 2024-11-03 at 8 55 55 PM" src="https://github.com/user-attachments/assets/521ac388-4d14-43d5-ad01-2e6b342bec1d">
This reaction might be considered as inconsistent response.

**Comment by FYL2003** [comment]
We can also write it into UG and state that for edit command to be a valid command, only positive integer is considered.

**Comment by FYL2003** [comment]
Addon : same issue for non-integer value

**Comment by casperngeen** [comment]
Closed by #210
