### ISSUE TITLE
AddEventCommand does not display error message for Duplicate Events

### ISSUE THREAD

**Issue by casperngeen** [AY2425S1-CS2103T-F13-3/tp#207]
When a duplicate description is given, a `RuntimeException` is thrown. Thus, there is no user feedback displayed and the app just hangs.

Steps:
1. Create a new event using `add -e` with a different `name` but the same for every other field
2. No response will be shown but in there will be a `RuntimeException` shown in the terminal

**Comment by yizhong187** [comment]
Can you give me the steps to reproduce the issue thanks!

**Comment by yizhong187** [comment]
To clarify, hang as in no response right?

**Comment by casperngeen** [comment]
> To clarify, hang as in no response right?

Yes, there is no update/feedback in the GUI
