### ISSUE TITLE
[PE-D][Tester B] Error message not complete

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-3/tp#237]
The "d/" field is not included in the usage example. Should add this field to the example usage
![image.png](https://raw.githubusercontent.com/YINZE66/ped/main/files/b5da6041-0020-41c7-95f8-9d3bc58cd8d0.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YINZE66/ped#2

**Comment by casperngeen** [comment]
`d/` is not a command flag for `Client`, this is expected.
