### ISSUE TITLE
[PE-D][Tester E] Contacts is not saved after exit command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-3/tp#273]
Blank address book is launched after I press exit command and open the app again.

![Screenshot 2024-11-08 at 5.30.18 PM.png](https://raw.githubusercontent.com/zeonchew0324/ped/main/files/78985ada-0ced-4105-937f-bafaadcb8ce3.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: zeonchew0324/ped#13

**Comment by casperngeen** [comment]
This behaviour cannot be replicated.
