### ISSUE TITLE
[PE-D][Tester A] Symbol Only Address Works

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-3/tp#274]
![image.png](https://raw.githubusercontent.com/Brendan8899/ped/main/files/e2442bd0-f342-4abb-b7bb-ed6cb4d249d7.png)

I tried editing address with " " which works. It shouldn't work. I think it can be solved with some custom Regex.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Brendan8899/ped#7

**Comment by casperngeen** [comment]
Any non-empty input is allowed.
