### ISSUE TITLE
Refactor usage of Person

### ISSUE THREAD

**Issue by leslieyip02** [AY2425S1-CS2103T-F13-3/tp#69]
## Description

Replace instances of `Person` in the codebase to use `Contact`, `Client` and `Vendor`.

- [x] `commons`
- [ ] `logic`
- [x] `model`
- [x] `storage`
- [x] `ui`
- [x] `resources`

For tests, comment out `Person` specific test cases for now since we have not finished implementing behaviour for `Contact`, `Client` and `Vendor`. Add `// TODO` comments so that we can revisit the test cases at a later milestone.

**Comment by FYL2003** [comment]
I don't think we need to update any other "Person" instances in the ui folder
